spring.application.name=hexagonal
server.port=${PORT:8080}

# Conexión a Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración del Pool Hikari (Evita timeouts inmediatos en Render)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Desactivar DDL por completo
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false

# Forzar Dialecto y desactivar validaciones en frío
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=true
